version: '3'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: "redis:alpine"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      